// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Andorra la Vella","Andorra la Vella",20430],
  ["les Escaldes","les Escaldes",15853],
] as const;
