// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Noord","Noord",24193],
  ["Oranjestad","Oranjestad",29998],
  ["Santa Cruz","Santa Cruz",15236],
  ["Tanki Leendert","Tanki Leendert",21500],
] as const;
