// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Al Muharraq","Al Muharraq",176583],
  ["Ar Rifā‘","Ar Rifa'",115495],
  ["Dār Kulayb","Dar Kulayb",65466],
  ["Jidd Ḩafş","Jidd Hafs",66588],
  ["Madīnat ‘Īsá","Madinat `Isa",38090],
  ["Madīnat Ḩamad","Madinat Hamad",133550],
  ["Manama","Manama",147074],
  ["Sitrah","Sitrah",72601],
] as const;
