// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Bubanza","Bubanza",30996],
  ["Bujumbura","Bujumbura",769317],
  ["Cendajuru","Cendajuru",32458],
  ["Cibitoke","Cibitoke",36959],
  ["Gatumba","Gatumba",18104],
  ["Gitega","Gitega",64904],
  ["Karusi","Karusi",15964],
  ["Kayanza","Kayanza",33682],
  ["Kirundo","Kirundo",15511],
  ["Mpanda","Mpanda",58913],
  ["Ngozi","Ngozi",61716],
  ["Rumonge","Rumonge",55599],
  ["Vyanda","Vyanda",29685],
  ["Zanandore","Zanandore",27867],
] as const;
