// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Bandar Seri Begawan","Bandar Seri Begawan",64409],
  ["Kuala Belait","Kuala Belait",31178],
  ["Liang","Liang",16813],
  ["Mentiri","Mentiri",39324],
  ["Sengkurong","Sengkurong",40972],
  ["Serasa","Serasa",18569],
  ["Seria","Seria",30097],
  ["Tutong","Tutong",19151],
] as const;
