// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Freeport","Freeport",26910],
  ["Killarney","Killarney",17679],
  ["Lucaya","Lucaya",46525],
  ["Nassau","Nassau",227940],
] as const;
