// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Phuntsholing","Phuntsholing",27658],
  ["Punākha","Punakha",21500],
  ["Thimphu","Thimphu",98676],
  ["Tsirang","Tsirang",22376],
] as const;
