// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Belize City","Belize City",65222],
  ["Belmopan","Belmopan",13381],
  ["Orange Walk","Orange Walk",15298],
  ["San Ignacio","San Ignacio",21229],
  ["San Pedro","San Pedro",17429],
] as const;
