// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Assomada","Assomada",21297],
  ["Espargos","Espargos",24500],
  ["Mindelo","Mindelo",69013],
  ["Praia","Praia",137868],
] as const;
