// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Aglantziá","Aglantzia",21543],
  ["Aradíppou","Aradippou",22934],
  ["Égkomi","Egkomi",20502],
  ["Famagusta","Famagusta",42526],
  ["Germasógeia","Germasogeia",17325],
  ["Káto Lakatámeia","Kato Lakatameia",40000],
  ["Káto Polemídia","Kato Polemidia",23231],
  ["Kyrenia","Kyrenia",26701],
  ["Larnaca","Larnaca",72000],
  ["Limassol","Limassol",154000],
  ["Mórfou","Morfou",24070],
  ["Nicosia","Nicosia",200452],
  ["Paphos","Paphos",35961],
  ["Protaras","Protaras",20230],
  ["Stróvolos","Strovolos",67904],
] as const;
