// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Ali Sabih","Ali Sabih",50006],
  ["Arta","Arta",17477],
  ["Balbala","Balbala",554350],
  ["Dikhil","Dikhil",32801],
  ["Djibouti","Djibouti",626512],
  ["Obock","Obock",15429],
  ["Tadjoura","Tadjoura",19533],
] as const;
