// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Haabersti","Haabersti",51423],
  ["Kesklinn","Kesklinn",67766],
  ["Kohtla-Järve","Kohtla-Jaerve",35395],
  ["Kristiine","Kristiine",34306],
  ["Lasnamäe","Lasnamaee",115008],
  ["Maardu","Maardu",16630],
  ["Mustamäe","Mustamaee",67968],
  ["Narva","Narva",54409],
  ["Nõmme","Nomme",39422],
  ["Pärnu","Paernu",40228],
  ["Pirita","Pirita",18310],
  ["Põhja-Tallinn","Pohja-Tallinn",63240],
  ["Tallinn","Tallinn",394024],
  ["Tartu","Tartu",91407],
  ["Viljandi","Viljandi",17407],
] as const;
