// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Boujdour","Boujdour",42651],
  ["Dakhla","Dakhla",106277],
  ["El Marsa","El Marsa",28848],
  ["Laayoune","Laayoune",196331],
] as const;
