// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Asmara","Asmara",563930],
  ["Assab","Assab",21300],
  ["Barentu","Barentu",15891],
  ["Himora","Himora",46100],
  ["Keren","Keren",74800],
  ["Massawa","Massawa",23100],
  ["Mendefera","Mendefera",17781],
] as const;
