// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Labasa","Labasa",27949],
  ["Lami","Lami",24639],
  ["Lautoka","Lautoka",52500],
  ["Nadi","Nadi",42284],
  ["Nasinu","Nasinu",92043],
  ["Sigatoka","Sigatoka",17622],
  ["Suva","Suva",77366],
] as const;
