// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Akanda","Akanda",41524],
  ["Bitam","Bitam",33561],
  ["Franceville","Franceville",132895],
  ["Koulamoutou","Koulamoutou",30830],
  ["Lambaréné","Lambarene",46605],
  ["Libreville","Libreville",846090],
  ["Makokou","Makokou",24823],
  ["Moanda","Moanda",71099],
  ["Mouila","Mouila",43342],
  ["Ntoum","Ntoum",62445],
  ["Owendo","Owendo",95313],
  ["Oyam","Oyam",30100],
  ["Oyem","Oyem",72939],
  ["Port-Gentil","Port-Gentil",164018],
  ["Tchibanga","Tchibanga",36108],
] as const;
