// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Akhaltsikhe","Akhaltsikhe",17445],
  ["Batumi","Batumi",186949],
  ["Gori","Gori",41933],
  ["Khashuri","Khashuri",23949],
  ["Kobuleti","Kobuleti",17538],
  ["Kutaisi","Kutaisi",135201],
  ["Marneuli","Marneuli",26400],
  ["Poti","Poti",41175],
  ["Rustavi","Rustavi",128249],
  ["Samtredia","Samtredia",20633],
  ["Sokhumi","Sokhumi",65439],
  ["Stantsiya Novyy Afon","Stantsiya Novyy Afon",26636],
  ["Tbilisi","Tbilisi",1049498],
  ["Telavi","Telavi",19875],
  ["Ts’khinvali","Ts'khinvali",32180],
  ["Zestaponi","Zestaponi",20183],
  ["Zugdidi","Zugdidi",40067],
] as const;
