// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Cayenne","Cayenne",61550],
  ["Kourou","Kourou",24029],
  ["Matoury","Matoury",26350],
  ["Rémire-Montjoly","Remire-Montjoly",19029],
  ["Saint-Laurent-du-Maroni","Saint-Laurent-du-Maroni",24287],
] as const;
