// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Baie-Mahault","Baie-Mahault",30837],
  ["Basse-Terre","Basse-Terre",11472],
  ["Capesterre-Belle-Eau","Capesterre-Belle-Eau",19821],
  ["Le Gosier","Le Gosier",28698],
  ["Le Moule","Le Moule",22692],
  ["Les Abymes","Les Abymes",53514],
  ["Petit-Bourg","Petit-Bourg",24994],
  ["Pointe-à-Pitre","Pointe-a-Pitre",15181],
  ["Sainte-Anne","Sainte-Anne",22859],
  ["Sainte-Rose","Sainte-Rose",20192],
] as const;
