// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Bata","Bata",173046],
  ["Ciudad de la Paz","Ciudad de la Paz",2000],
  ["Ebebiyin","Ebebiyin",24831],
  ["Malabo","Malabo",155963],
] as const;
