// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Dededo Village","Dededo Village",44943],
  ["Hagåtña","Hagatna",1051],
  ["Mangilao Village","Mangilao Village",15191],
  ["Tamuning","Tamuning",19685],
  ["Tamuning-Tumon-Harmon Village","Tamuning-Tumon-Harmon Village",19685],
  ["Yigo Village","Yigo Village",20539],
] as const;
