// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Bafatá","Bafata",33502],
  ["Bairro Militar","Bairro Militar",65274],
  ["Belem","Belem",17263],
  ["Bissau","Bissau",439704],
  ["Contumo","Contumo",45482],
  ["Gabú","Gabu",49371],
  ["Luanda","Luanda",25236],
  ["Missira","Missira",38838],
  ["Plaque","Plaque",27633],
  ["Quelele","Quelele",28898],
  ["Reino de Antula","Reino de Antula",30778],
  ["Reino de Bandim","Reino de Bandim",44718],
  ["Santa-Luzia","Santa-Luzia",17204],
  ["Sintra-Nema","Sintra-Nema",21451],
  ["Xitole","Xitole",19424],
] as const;
