// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Georgetown","Georgetown",235017],
  ["Linden","Linden",44690],
  ["New Amsterdam","New Amsterdam",35039],
] as const;
