// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Akureyri","Akureyri",19219],
  ["Hafnarfjörður","Hafnarfjoerdur",31525],
  ["Keflavík","Keflavik",15930],
  ["Kópavogur","Kopavogur",40040],
  ["Reykjanesbær","Reykjanesbaer",19724],
  ["Reykjavík","Reykjavik",118918],
] as const;
