// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Barrett Town","Barrett Town",17169],
  ["Half Way Tree","Half Way Tree",18552],
  ["Kingston","Kingston",937700],
  ["Linstead","Linstead",20660],
  ["Mandeville","Mandeville",47115],
  ["May Pen","May Pen",44755],
  ["Montego Bay","Montego Bay",82867],
  ["New Kingston","New Kingston",583958],
  ["Ocho Rios","Ocho Rios",26503],
  ["Old Harbour","Old Harbour",26024],
  ["Portmore","Portmore",102861],
  ["Savanna-la-Mar","Savanna-la-Mar",16553],
  ["Spanish Town","Spanish Town",145018],
] as const;
