// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Ad Dasmah","Ad Dasmah",17585],
  ["Al Aḩmadī","Al Ahmadi",637411],
  ["Al Faḩāḩīl","Al Fahahil",68290],
  ["Al Farwānīyah","Al Farwaniyah",86525],
  ["Al Finţās","Al Fintas",23071],
  ["Al Jahrā’","Al Jahra'",24281],
  ["Al Mahbūlah","Al Mahbulah",18178],
  ["Al Manqaf","Al Manqaf",39025],
  ["Ar Rābiyah","Ar Rabiyah",36447],
  ["Ar Riqqah","Ar Riqqah",52068],
  ["Ar Rumaythīyah","Ar Rumaythiyah",58135],
  ["As Sālimīyah","As Salimiyah",147649],
  ["Bayān","Bayan",30635],
  ["Ḩawallī","Hawalli",164212],
  ["Janūb as Surrah","Janub as Surrah",18496],
  ["Kuwait City","Kuwait City",60064],
  ["Şabāḩ as Sālim","Sabah as Salim",139163],
  ["Salwá","Salwa",40945],
] as const;
