// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Ban Houakhoua","Ban Houakhoua",15500],
  ["Ban Kèngkok","Ban Kengkok",15658],
  ["Ban Khoan","Ban Khoan",65348],
  ["Ban Laongam","Ban Laongam",21304],
  ["Ban Xénô","Ban Xeno",25135],
  ["Borikhan","Borikhan",18354],
  ["Luang Prabang","Luang Prabang",55027],
  ["Muang Phônsavan","Muang Phonsavan",37507],
  ["Muang Sing","Muang Sing",23500],
  ["Muang Xay","Muang Xay",25000],
  ["Pakse","Pakse",77900],
  ["Pakxan","Pakxan",21967],
  ["Savannakhet","Savannakhet",125760],
  ["Sekong","Sekong",20116],
  ["Thakhèk","Thakhek",90800],
  ["Vang Vieng","Vang Vieng",25000],
  ["Vientiane","Vientiane",840940],
  ["Xam Nua","Xam Nua",56900],
] as const;
