// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Aarsâl","Aarsal",50000],
  ["Aley","Aley",130000],
  ["Baalbek","Baalbek",30916],
  ["Beirut","Beirut",1916100],
  ["Bsharri","Bsharri",20000],
  ["Byblos","Byblos",20784],
  ["Chmistâr","Chmistar",30000],
  ["El Hermel","El Hermel",22250],
  ["En Nâqoûra","En Naqoura",24910],
  ["Ghazieh","Ghazieh",50000],
  ["Habboûch","Habbouch",98433],
  ["Jounieh","Jounieh",96315],
  ["Nabatîyé et Tahta","Nabatiye et Tahta",120000],
  ["Ra’s Bayrūt","Ra's Bayrut",1251739],
  ["Sidon","Sidon",163554],
  ["Tripoli","Tripoli",229398],
  ["Tyre","Tyre",135204],
  ["Zahlé","Zahle",78145],
] as const;
