// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Buchanan","Buchanan",75854],
  ["Foya Kamara","Foya Kamara",31052],
  ["Ganta","Ganta",63523],
  ["Gbarnga","Gbarnga",86031],
  ["Greenville","Greenville",20184],
  ["Harbel","Harbel",38208],
  ["Harper","Harper",35503],
  ["Kakata","Kakata",52247],
  ["Monrovia","Monrovia",1542549],
  ["New Yekepa","New Yekepa",24695],
  ["Pleebo City","Pleebo City",35423],
  ["Saclepea","Saclepea",20818],
  ["Sanniquellie","Sanniquellie",17895],
  ["Tubmanburg","Tubmanburg",22005],
  ["Voinjama","Voinjama",23051],
  ["Zwedru","Zwedru",38269],
] as const;
