// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Butha-Buthe","Butha-Buthe",40599],
  ["Hlotse","Hlotse",43967],
  ["Mabote","Mabote",38047],
  ["Mafeteng","Mafeteng",45287],
  ["Maputsoe","Maputsoe",61916],
  ["Maseru","Maseru",359753],
  ["Mohale's Hoek","Mohale's Hoek",46593],
  ["Qacha’s Nek","Qacha's Nek",25573],
  ["Quthing","Quthing",33910],
  ["Teyateyaneng","Teyateyaneng",27272],
  ["Thaba-Tseka","Thaba-Tseka",16765],
] as const;
