// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Dudelange","Dudelange",18013],
  ["Esch-sur-Alzette","Esch-sur-Alzette",36625],
  ["Luxembourg","Luxembourg",76684],
] as const;
