// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Cēsis","Cesis",15020],
  ["Dārzciems","Darzciems",17599],
  ["Daugavpils","Daugavpils",78126],
  ["Jēkabpils","Jekabpils",21014],
  ["Jelgava","Jelgava",54834],
  ["Jūrmala","Jurmala",52001],
  ["Liepāja","Liepaja",67421],
  ["Mārupe","Marupe",19096],
  ["Ogre","Ogre",22767],
  ["Rēzekne","Rezekne",26429],
  ["Riga","Riga",742572],
  ["Salaspils","Salaspils",17826],
  ["Tukums","Tukums",16182],
  ["Valmiera","Valmiera",22812],
  ["Ventspils","Ventspils",32723],
] as const;
