// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Monaco","Monaco",32965],
  ["Monte-Carlo","Monte-Carlo",16012],
] as const;
