// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Bar","Bar",17727],
  ["Bijelo Polje","Bijelo Polje",15400],
  ["Budva","Budva",18000],
  ["Cetinje","Cetinje",15137],
  ["Herceg Novi","Herceg Novi",19536],
  ["Nikšić","Niksic",58212],
  ["Pljevlja","Pljevlja",19489],
  ["Podgorica","Podgorica",236852],
] as const;
