// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Dalap-Uliga-Dorrit","Dalap-Uliga-Dorrit",20301],
  ["Majuro","Majuro",25400],
] as const;
