// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Lai Chi Van","Lai Chi Van",22125],
  ["Luhuan","Luhuan",36384],
  ["Macau","Macau",649335],
  ["Sé","Se",52200],
  ["Taipa","Taipa",112051],
  ["Zhuojiacun","Zhuojiacun",24000],
] as const;
