// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Ducos","Ducos",17394],
  ["Fort-de-France","Fort-de-France",89995],
  ["La Trinité","La Trinite",15040],
  ["Le François","Le Francois",19682],
  ["Le Lamentin","Le Lamentin",40581],
  ["Le Robert","Le Robert",23814],
  ["Saint-Joseph","Saint-Joseph",16974],
  ["Sainte-Marie","Sainte-Marie",20380],
] as const;
