// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Birkirkara","Birkirkara",24356],
  ["Mosta","Mosta",23482],
  ["Qormi","Qormi",16801],
  ["San Pawl il-Baħar","San Pawl il-Bahar",32042],
  ["Sliema","Sliema",22591],
  ["Valletta","Valletta",6794],
  ["Żabbar","Zabbar",15648],
] as const;
