// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Baie du Tombeau","Baie du Tombeau",15301],
  ["Bambous","Bambous",17818],
  ["Beau Bassin-Rose Hill","Beau Bassin-Rose Hill",111355],
  ["Bel Air Rivière Sèche","Bel Air Riviere Seche",18036],
  ["Centre de Flacq","Centre de Flacq",17710],
  ["Curepipe","Curepipe",78618],
  ["Goodlands","Goodlands",21063],
  ["Le Hochet","Le Hochet",15662],
  ["Mahébourg","Mahebourg",17042],
  ["Port Louis","Port Louis",155226],
  ["Quatre Bornes","Quatre Bornes",77308],
  ["Saint Pierre","Saint Pierre",16704],
  ["Triolet","Triolet",24361],
  ["Vacoas","Vacoas",115289],
] as const;
