// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Gobabis","Gobabis",22639],
  ["Grootfontein","Grootfontein",24099],
  ["Helao Nafidi","Helao Nafidi",22963],
  ["Katima Mulilo","Katima Mulilo",33615],
  ["Katutura","Katutura",21243],
  ["Keetmanshoop","Keetmanshoop",23049],
  ["Lüderitz","Luderitz",15137],
  ["Ndiyona","Ndiyona",20633],
  ["Okahandja","Okahandja",26832],
  ["Ondangwa","Ondangwa",27049],
  ["Ongwediva","Ongwediva",24012],
  ["Oshakati","Oshakati",43309],
  ["Otjiwarongo","Otjiwarongo",33481],
  ["Rehoboth","Rehoboth",34185],
  ["Rundu","Rundu",75180],
  ["Swakopmund","Swakopmund",53009],
  ["Tsumeb","Tsumeb",22845],
  ["Walvis Bay","Walvis Bay",73598],
  ["Windhoek","Windhoek",386219],
] as const;
