// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Dumbéa","Dumbea",19346],
  ["Mont-Dore","Mont-Dore",24680],
  ["Nouméa","Noumea",93060],
] as const;
