// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Faaa","Faaa",29851],
  ["Papeete","Papeete",26357],
  ["Punaauia","Punaauia",25750],
] as const;
