// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Arawa","Arawa",40266],
  ["Bulolo","Bulolo",16042],
  ["Daru","Daru",15214],
  ["Goroka","Goroka",18503],
  ["Kimbe","Kimbe",18847],
  ["Kokopo","Kokopo",26273],
  ["Lae","Lae",76255],
  ["Madang","Madang",27419],
  ["Mendi","Mendi",26252],
  ["Mount Hagen","Mount Hagen",33623],
  ["Popondetta","Popondetta",28198],
  ["Port Moresby","Port Moresby",283733],
  ["Wewak","Wewak",18230],
] as const;
