// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["La Possession","La Possession",35245],
  ["Le Port","Le Port",33336],
  ["Le Tampon","Le Tampon",81943],
  ["Piton Saint-Leu","Piton Saint-Leu",29278],
  ["Saint-André","Saint-Andre",57150],
  ["Saint-Benoît","Saint-Benoit",37023],
  ["Saint-Denis","Saint-Denis",154765],
  ["Saint-Joseph","Saint-Joseph",38807],
  ["Saint-Leu","Saint-Leu",34893],
  ["Saint-Louis","Saint-Louis",53935],
  ["Saint-Paul","Saint-Paul",105240],
  ["Saint-Pierre","Saint-Pierre",84077],
  ["Sainte-Marie","Sainte-Marie",34344],
  ["Sainte-Suzanne","Sainte-Suzanne",24293],
] as const;
