// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Honiara","Honiara",56298],
  ["Kola'a","Kola'a",20783],
  ["Malango","Malango",15560],
  ["Nggosi","Nggosi",26009],
  ["Panatina","Panatina",32712],
  ["Tandai","Tandai",24592],
  ["Vura","Vura",18753],
] as const;
