// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Celje","Celje",38059],
  ["Koper","Koper",25753],
  ["Kranj","Kranj",37966],
  ["Ljubljana","Ljubljana",272220],
  ["Maribor","Maribor",96209],
  ["Novo Mesto","Novo Mesto",24446],
  ["Ptuj","Ptuj",17984],
  ["Trbovlje","Trbovlje",15163],
  ["Velenje","Velenje",24327],
] as const;
