// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Bo","Bo",233684],
  ["Bumpe","Bumpe",16123],
  ["Freetown","Freetown",802639],
  ["Goderich","Goderich",19209],
  ["Kabala","Kabala",17948],
  ["Kenema","Kenema",255110],
  ["Koidu","Koidu",128030],
  ["Lunsar","Lunsar",22461],
  ["Makeni","Makeni",85116],
  ["Mile 91","Mile 91",15491],
  ["Njala","Njala",40000],
  ["Port Loko","Port Loko",44900],
  ["Segbwema","Segbwema",16532],
  ["Waterloo","Waterloo",55000],
] as const;
