// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Beekhuizen","Beekhuizen",17185],
  ["Blauwgrond","Blauwgrond",31483],
  ["Flora","Flora",19538],
  ["Latour","Latour",29526],
  ["Lelydorp","Lelydorp",18223],
  ["Munder Buiten","Munder Buiten",17234],
  ["Paramaribo","Paramaribo",223757],
  ["Pontbuiten","Pontbuiten",23211],
  ["Rainville","Rainville",22747],
  ["Tammenga","Tammenga",15819],
  ["Weg naar Zee","Weg naar Zee",16037],
  ["Welgelegen","Welgelegen",19304],
] as const;
