// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Aweil","Aweil",38745],
  ["Bor","Bor",26782],
  ["Gogrial","Gogrial",44600],
  ["Juba","Juba",450000],
  ["Kafia Kingi","Kafia Kingi",16000],
  ["Kuacjok","Kuacjok",78000],
  ["Leer","Leer",17827],
  ["Malakal","Malakal",160765],
  ["Pajok","Pajok",49000],
  ["Rumbek","Rumbek",32083],
  ["Tonj","Tonj",17338],
  ["Torit","Torit",20048],
  ["Wau","Wau",127384],
  ["Winejok","Winejok",300000],
  ["Yambio","Yambio",40382],
  ["Yei","Yei",260720],
] as const;
