// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Aného","Aneho",47579],
  ["Anié","Anie",37398],
  ["Atakpamé","Atakpame",80683],
  ["Badou","Badou",24000],
  ["Bafilo","Bafilo",22543],
  ["Bassar","Bassar",61845],
  ["Dapaong","Dapaong",58071],
  ["Kara","Kara",104207],
  ["Kpalimé","Kpalime",75084],
  ["Lomé","Lome",2188376],
  ["Mango","Mango",37748],
  ["Niamtougou","Niamtougou",23261],
  ["Notsé","Notse",35039],
  ["Sinkassé","Sinkasse",26926],
  ["Sokodé","Sokode",117811],
  ["Sotouboua","Sotouboua",24332],
  ["Tabligbo","Tabligbo",22304],
  ["Tchamba","Tchamba",25668],
  ["Tsévié","Tsevie",55775],
  ["Vogan","Vogan",20569],
] as const;
