// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Aileu","Aileu",17356],
  ["Atsabe","Atsabe",16304],
  ["Baukau","Baukau",16000],
  ["Dili","Dili",150000],
  ["Likisá","Likisa",19000],
  ["Lospalos","Lospalos",17186],
  ["Maliana","Maliana",22000],
  ["Maubara","Maubara",16300],
  ["Suai","Suai",21539],
  ["Venilale","Venilale",16000],
] as const;
