// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Arima","Arima",35000],
  ["Chaguanas","Chaguanas",67433],
  ["Diego Martin","Diego Martin",25370],
  ["Laventille","Laventille",21000],
  ["Marabella","Marabella",26700],
  ["Mon Repos","Mon Repos",56380],
  ["Paradise","Paradise",15067],
  ["Point Fortin","Point Fortin",19056],
  ["Port of Spain","Port of Spain",49031],
  ["Rio Claro","Rio Claro",35650],
  ["San Fernando","San Fernando",55419],
  ["Sangre Grande","Sangre Grande",15968],
  ["Scarborough","Scarborough",17000],
  ["Tunapuna","Tunapuna",17758],
] as const;
