// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Charlotte Amalie","Charlotte Amalie",20000],
  ["Saint Croix","Saint Croix",50601],
] as const;
