// Generated by scripts/generate-city-catalog.js from GeoNames "cities15000" (CC BY 4.0).
// See docs/data-sources/geonames-cities.md. Do not edit by hand — regenerate instead.
export const cities = [
  ["Dzaoudzi","Dzaoudzi",15339],
  ["Kaouéni","Kaoueni",17060],
  ["Koungou","Koungou",18118],
  ["Labattoir","Labattoir",17739],
  ["Mamoudzou","Mamoudzou",54831],
  ["Mtsapéré","Mtsapere",15880],
] as const;
